CREATE TABLE APP.Users(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
username VARCHAR(45) NOT NULL UNIQUE,
password VARCHAR(45) NOT NULL,
email VARCHAR (45) NOT NULL,
notificationAllow  INT NOT NULL CHECK(notificationAllow>=0 AND notificationAllow<=1) DEFAULT 0,
levelNo SMALLINT NOT NULL DEFAULT 1,
score INT NOT NULL DEFAULT 0,
choosen_weapon_id INT NOT NULL DEFAULT 1,
last_activity_on TIMESTAMP ,
PRIMARY KEY(id)
);

CREATE TABLE APP.Weapons(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
damage INT NOT NULL DEFAULT 0,
price INT NOT NULL DEFAULT 0,
PRIMARY KEY(id)
);

CREATE TABLE APP.UnlockedWeapons( 
user_id INT NOT NULL ,
weapon_id INT NOT NULL,
PRIMARY KEY(user_id, weapon_id),
FOREIGN KEY(weapon_id) REFERENCES app.Weapons (id) ,
FOREIGN KEY(user_id) REFERENCES app.Users (id) 
);

CREATE TABLE APP.Boosters(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
duration BIGINT NOT NULL,
description VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE app.Achievements (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
achievement_points INT NOT NULL,
description VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE app.UserAchievements(
user_id INT NOT NULL ,
achievement_id INT NOT NULL,
PRIMARY KEY(user_id, achievement_id),
FOREIGN KEY(achievement_id) REFERENCES app.Achievements (id) ,
FOREIGN KEY(user_id) REFERENCES app.Users (id)
);
